# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bGuIz8TzIhnO7C0naWdBEpVyQWXuN6h3
"""


import streamlit as st
from converter import convert_pdf_to_docx
import os

st.title("PDF to Word Converter")

uploaded_file = st.file_uploader(
    "Upload PDF",
    type=["pdf"]
)

if uploaded_file:

    st.success("PDF Uploaded Successfully")

    if st.button("Convert to Word"):

        output_file = convert_pdf_to_docx(uploaded_file)

        pdf_to_word(
            uploaded_file,
            output_file
        )

        st.success("Conversion Complete")

        with open(output_file, "rb") as file:

            st.download_button(
                label="Download Word File",
                data=file,
                file_name="converted.docx",
                mime="application/vnd.openxmlformats-officedocument.wordprocessingml.document"
            )
