# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bGuIz8TzIhnO7C0naWdBEpVyQWXuN6h3
"""
import streamlit as st
from converter import convert_pdf_to_docx

# Page Config
st.set_page_config(
    page_title="PDF to Word Converter",
    page_icon="📄",
    layout="centered"
)

# Title
st.title("📄 PDF to Word Converter")
st.write("Upload a PDF file and convert it into an editable Word document.")

# File Upload
uploaded_file = st.file_uploader(
    "Upload PDF",
    type=["pdf"]
)



# Conversion Logic
if uploaded_file is not None:

    st.success("✅ PDF Uploaded Successfully")
    st.info(f"""
    File Name: {uploaded_file.name}
    
    Size: {round(uploaded_file.size/1024,2)} KB
    """)
    if st.button("Convert to Word"):

        try:

            with st.spinner("Converting PDF to Word..."):

                output_file = convert_pdf_to_docx(uploaded_file)

            st.success("🎉 Conversion Completed Successfully!")

            with open(output_file, "rb") as file:
                file_name = uploaded_file.name.replace(".pdf",".docx")

                st.download_button(
                    label="📥 Download DOCX",
                    data=file,
                    file_name=file_name,
                    mime="application/vnd.openxmlformats-officedocument.wordprocessingml.document"
                )

        except Exception as e:

            st.error(f"❌ Error: {str(e)}")

# Footer
st.markdown("---")
st.caption("Built with ❤️ using Streamlit and Python")
