# -*- coding: utf-8 -*-
"""Converter

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XHiHH9ZpgI7kQWopBsbUYivXFf5oUahR
"""

!pip install streamlit pymupdf python-docx
import fitz
from docx import Document

def convert_pdf_to_docx(uploaded_file):

    pdf = fitz.open(
        stream=uploaded_file.read(),
        filetype="pdf"
    )

    doc = Document()

    for page in pdf:
        text = page.get_text()
        doc.add_paragraph(text)

    output_path = "output.docx"

    doc.save(output_path)

    return output_path