# -*- coding: utf-8 -*-
"""Converter

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XHiHH9ZpgI7kQWopBsbUYivXFf5oUahR
"""


from pdf2docx import Converter

def convert_pdf_to_docx(uploaded_file):

    pdf_path = "temp.pdf"

    with open(pdf_path, "wb") as f:
        f.write(uploaded_file.getbuffer())

    docx_path = "converted.docx"

    cv = Converter(pdf_path)
    cv.convert(docx_path)
    cv.close()

    return docx_path
